 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-deploy
  labels:
    app: ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws
  template:
    metadata:
      labels:
        app: ws
    spec:
      containers:
      - name: ws
        image: leopold9707/restful:latest
        ports:
        - containerPort: 8080
